---
# Interfaces detectadas via `ip -4 addr show` na nat-gw:
# eth0 (altname ens18) = privada 10.0.0.1/24
# eth1 (altname ens19) = publica  177.91.66.34/29
private_interface: eth0
public_interface: eth1
