server {
    listen 177.91.66.37:80 default_server;
    server_name grafana.k8s.homolog 177.91.66.37;

    location / {
        rewrite ^(/.*)$ /grafana$1 break;
        proxy_pass http://10.0.0.201:80;
        proxy_http_version 1.1;
        proxy_set_header Host "grafana.k8s.homolog";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Accept-Encoding "identity";
    }
}

server {
    listen 177.91.66.38:80;
    server_name zabbix.k8s.homolog 177.91.66.38;

    location / {
        rewrite ^(/.*)$ /zabbix$1 break;
        proxy_pass http://10.0.0.201:80;
        proxy_http_version 1.1;
        proxy_set_header Host "zabbix.k8s.homolog";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Accept-Encoding "identity";
        sub_filter 'href="/' 'href="/zabbix/';
        sub_filter 'src="/' 'src="/zabbix/';
        sub_filter 'action="/' 'action="/zabbix/';
        sub_filter 'href="assets/' 'href="/zabbix/assets/';
        sub_filter 'src="assets/' 'src="/zabbix/assets/';
        sub_filter 'href="js/' 'href="/zabbix/js/';
        sub_filter 'src="js/' 'src="/zabbix/js/';
        sub_filter 'href="fonts/' 'href="/zabbix/fonts/';
        sub_filter 'href="img/' 'href="/zabbix/img/';
        sub_filter 'href="images/' 'href="/zabbix/images/';
        sub_filter 'href="favicon.ico' 'href="/zabbix/favicon.ico';
        sub_filter 'href="index.php' 'href="/zabbix/index.php';
        sub_filter 'action="index.php' 'action="/zabbix/index.php';
        sub_filter_once off;
        sub_filter_types text/html application/json;
    }
}
